import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import type {
  AnalyticsReport,
  SummaryStats,
} from "./ReportTypes";

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 14;

const COLORS = {
  primary: [0, 150, 136] as [number, number, number],
  secondary: [52, 73, 94] as [number, number, number],
  border: [220, 220, 220] as [number, number, number],
  light: [247, 249, 250] as [number, number, number],
  dark: [40, 40, 40] as [number, number, number],
};

const formatNumber = (value: number) =>
  value.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const currency = (value: number) =>
  `INR ${formatNumber(value)}`;



function buildSummaryTable(
  report: AnalyticsReport
) {
  return [
    ["Total Sessions", report.summary.totalSessions],
    [
      "Total Energy",
      `${formatNumber(report.summary.totalEnergy)} kWh`,
    ],
    [
      "Total Spend",
      currency(report.summary.totalCost),
    ],
    [
      "Average Energy",
      `${formatNumber(report.summary.averageEnergy)} kWh`,
    ],
    [
      "Average Cost",
      currency(report.summary.averageCost),
    ],
    [
      "Estimated Range",
      `${formatNumber(report.summary.estimatedRange)} km`,
    ],
    [
      "Petrol Saved",
      `${formatNumber(report.summary.petrolSaved)} L`,
    ],
    [
      "Carbon Saved",
      `${formatNumber(report.summary.carbonSaved)} kg`,
    ],
  ];
}

function buildStatsTable(
  stats: Record<string, SummaryStats>
) {
  return Object.entries(stats).map(
    ([name, value]) => [
      name,
      value.sessions,
      formatNumber(value.energy),
      currency(value.cost),
    ]
  );
}

function defaultTableTheme() {
  return {
    theme: "striped" as const,

    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 3,
      lineColor: COLORS.border,
    },

    headStyles: {
      fillColor: COLORS.primary,
      textColor: 255,
      fontStyle: "bold" as const,
    },

    alternateRowStyles: {
      fillColor: COLORS.light,
    },
  };
}

function addCoverPage(
    pdf: jsPDF,
    report: AnalyticsReport
  ) {
    const vehicle =
      Object.keys(report.vehicles)[0] ?? "N/A";
  
    // Header Banner
    pdf.setFillColor(...COLORS.primary);
    pdf.rect(0, 0, PAGE_WIDTH, 48, "F");
  
    pdf.setTextColor(255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(28);
    pdf.text("EV Toolkit", PAGE_WIDTH / 2, 22, {
      align: "center",
    });
  
    pdf.setFontSize(18);
    pdf.text(
      "Charging Analytics Report",
      PAGE_WIDTH / 2,
      35,
      {
        align: "center",
      }
    );
  
    pdf.setTextColor(...COLORS.dark);
  
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);
    pdf.text("Report Information", 20, 68);
  
    autoTable(pdf, {
      startY: 75,
  
      theme: "grid",
  
      head: [["Field", "Value"]],
  
      body: [
        [
          "Generated On",
          report.generatedOn.toLocaleString(),
        ],
        [
          "Prepared By",
          "EV Toolkit",
        ],
        [
          "Vehicle",
          vehicle,
        ],
        [
          "Total Sessions",
          report.summary.totalSessions,
        ],
        [
          "Total Energy",
          `${formatNumber(
            report.summary.totalEnergy
          )} kWh`,
        ],
        [
          "Total Spend",
          currency(report.summary.totalCost),
        ],
        [
          "Estimated Range",
          `${formatNumber(
            report.summary.estimatedRange
          )} km`,
        ],
        [
          "Petrol Saved",
          `${formatNumber(
            report.summary.petrolSaved
          )} L`,
        ],
        [
          "Carbon Saved",
          `${formatNumber(
            report.summary.carbonSaved
          )} kg`,
        ],
      ],
  
      headStyles: {
        fillColor: COLORS.primary,
        textColor: 255,
      },
  
      styles: {
        fontSize: 11,
        cellPadding: 4,
      },
  
      margin: {
        left: 20,
        right: 20,
      },
    });
  
    pdf.setDrawColor(...COLORS.border);
  
    pdf.line(
      20,
      270,
      PAGE_WIDTH - 20,
      270
    );
  
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(10);
  
    pdf.text(
      "Confidential • Generated by EV Toolkit",
      PAGE_WIDTH / 2,
      278,
      {
        align: "center",
      }
    );
  }
  
  function addHeader(pdf: jsPDF) {
    pdf.setFillColor(...COLORS.primary);
  
    pdf.rect(
      0,
      0,
      PAGE_WIDTH,
      18,
      "F"
    );
  
    pdf.setTextColor(255);
  
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
  
    pdf.text(
      "EV Toolkit",
      14,
      12
    );
  
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
  
    pdf.text(
      "Charging Analytics Report",
      PAGE_WIDTH - 14,
      12,
      {
        align: "right",
      }
    );
  
    pdf.setTextColor(...COLORS.dark);
  }
  
  function addFooter(
    pdf: jsPDF,
    report: AnalyticsReport,
    page: number,
    totalPages: number
  ) {
    pdf.setDrawColor(...COLORS.border);
  
    pdf.line(
      MARGIN,
      PAGE_HEIGHT - 14,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - 14
    );
  
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
  
    pdf.text(
      `Generated: ${report.generatedOn.toLocaleString()}`,
      MARGIN,
      PAGE_HEIGHT - 7
    );
  
    pdf.text(
      `Page ${page} of ${totalPages}`,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - 7,
      {
        align: "right",
      }
    );
  }
  
  function sectionTitle(
    pdf: jsPDF,
    title: string,
    y: number
  ) {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(17);
  
    pdf.text(
      title,
      MARGIN,
      y
    );
  
    pdf.setDrawColor(...COLORS.primary);
  
    pdf.line(
      MARGIN,
      y + 2,
      PAGE_WIDTH - MARGIN,
      y + 2
    );
  }

export async function exportPDF(
  report: AnalyticsReport,
  charts: string[]
) {
  const pdf = new jsPDF();

  addCoverPage(pdf, report);

  pdf.addPage();

    // Executive Summary
addHeader(pdf);

sectionTitle(pdf, "Executive Summary", 28);

autoTable(pdf, {
  startY: 34,
  head: [["Metric", "Value"]],
  body: buildSummaryTable(report),
  ...defaultTableTheme(),
});


// ----------------------------------------------------------------
// Vehicle Statistics
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(pdf, "Vehicle Statistics", 28);

autoTable(pdf, {
  startY: 34,

  head: [["Vehicle", "Sessions", "Energy (kWh)", "Spend"]],

  body: buildStatsTable(report.vehicles),

  foot: [[
    "TOTAL",
    report.summary.totalSessions,
    formatNumber(report.summary.totalEnergy),
    currency(report.summary.totalCost),
  ]],

  footStyles: {
    fillColor: [235,235,235],
    textColor: 0,
    fontStyle: "bold" as const,
  },

  ...defaultTableTheme(),
});


// ----------------------------------------------------------------
// Charging Station Statistics
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(pdf, "Charging Station Statistics", 28);

autoTable(pdf, {
  startY: 34,

  head: [["Station","Sessions","Energy (kWh)","Spend"]],

  body: buildStatsTable(report.stations),

  ...defaultTableTheme(),
});


// ----------------------------------------------------------------
// Monthly Summary
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(pdf, "Monthly Summary", 28);

autoTable(pdf, {
  startY: 34,

  head: [["Month","Sessions","Energy (kWh)","Spend"]],

  body: buildStatsTable(report.monthly),

  foot: [[
    "TOTAL",
    report.summary.totalSessions,
    formatNumber(report.summary.totalEnergy),
    currency(report.summary.totalCost),
  ]],

  footStyles: {
    fillColor: [235,235,235],
    textColor: 0,
    fontStyle: "bold" as const,
  },

  ...defaultTableTheme(),
});


// ----------------------------------------------------------------
// Yearly Summary
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(pdf, "Yearly Summary", 28);

autoTable(pdf, {
  startY: 34,

  head: [["Year","Sessions","Energy (kWh)","Spend"]],

  body: buildStatsTable(report.yearly),

  ...defaultTableTheme(),
});


// ----------------------------------------------------------------
// Weekly Summary
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(pdf, "Weekly Summary", 28);

autoTable(pdf, {
  startY: 34,

  head: [["Day","Sessions"]],

  body: Object.entries(report.weekly).map(
    ([day, sessions]) => [
      day,
      sessions,
    ]
  ),

  ...defaultTableTheme(),
});
  
      // Monthly Spend Trend
      const chartTitles = [
        "Monthly Spend Trend",
        "Monthly Energy Trend",
        "Weekly Sessions",
        "Charging Type Distribution",
      ];
      
      charts.forEach((chart, index) => {
        if (!chart) return;
      
        pdf.addPage();
      
        addHeader(pdf);
      
        sectionTitle(
          pdf,
          chartTitles[index] ?? `Chart ${index + 1}`,
          28
        );
      
        pdf.setDrawColor(...COLORS.border);
        pdf.setLineWidth(0.4);
      
        pdf.roundedRect(
          18,
          36,
          174,
          118,
          3,
          3
        );
      
        pdf.addImage(
          chart,
          "PNG",
          24,
          42,
          162,
          106,
          undefined,
          "FAST"
        );
      
        pdf.setFont("helvetica", "italic");
        pdf.setFontSize(9);
      
        pdf.setTextColor(110);
      
        pdf.text(
          "Generated from EV Toolkit analytics",
          PAGE_WIDTH / 2,
          164,
          {
            align: "center",
          }
        );
      
        pdf.setTextColor(...COLORS.dark);
      });

 // ----------------------------------------------------------------
// Charging Session History
// ----------------------------------------------------------------

pdf.addPage();

addHeader(pdf);

sectionTitle(
  pdf,
  "Charging Session History",
  28
);

autoTable(pdf, {
  startY: 34,

  margin: {
    top: 34,
    left: MARGIN,
    right: MARGIN,
  },

  head: [[
    "#",
    "Date",
    "Vehicle",
    "Station",
    "Charger",
    "Energy",
    "Spend",
  ]],

  body: report.sessions.map((session, index) => [
    index + 1,
    session.date,
    session.vehicle,
    session.station,
    session.charger,
    `${formatNumber(session.energy)} kWh`,
    currency(session.cost),
  ]),

  ...defaultTableTheme(),

  styles: {
    ...defaultTableTheme().styles,
    fontSize: 8,
    cellPadding: 2.5,
    overflow: "linebreak",
    valign: "middle",
  },

  headStyles: {
    fillColor: COLORS.primary,
    textColor: 255,
    fontStyle: "bold" as const,
  },

  alternateRowStyles: {
    fillColor: COLORS.light,
  },

  columnStyles: {
    0: {
      cellWidth: 10,
      halign: "center",
    },

    1: {
      cellWidth: 25,
    },

    2: {
      cellWidth: 28,
    },

    3: {
      cellWidth: 48,
    },

    4: {
      cellWidth: 28,
    },

    5: {
      cellWidth: 25,
      halign: "right",
    },

    6: {
      cellWidth: 28,
      halign: "right",
    },
  },

  willDrawPage: (data) => {
    addHeader(pdf);

    // Draw the title only on the FIRST page of this table
    if (data.pageNumber === 1) {
      sectionTitle(
        pdf,
        "Charging Session History",
        28
      );
    }
  },
});

    // ------------------------------------------------------------
// Finalize all pages
// ------------------------------------------------------------

const totalPages = pdf.getNumberOfPages();

for (let page = 2; page <= totalPages; page++) {
  pdf.setPage(page);

  // Footer only (headers are already drawn when pages are created)
  addFooter(
    pdf,
    report,
    page - 1,
    totalPages - 1
  );
}

// Keep cover page clean
pdf.setPage(1);

return pdf;
  }
  